-- ===========================================================================
-- PitchRooms — demo accounts (TEST DATA)
-- Generated by bin/build-demo-sql.php on 2026-09-24 08:50:34 UTC
--
-- Import after install.sql. Passwords: demo123, and admin123 for the admin.
-- Delete these accounts before the platform goes live.
-- ===========================================================================

SET NAMES utf8mb4;

INSERT INTO users (id, panel_id, role, first_name, last_name, name, email, password_hash,
                   phone, country, company, title, email_verified_at, phone_verified_at,
                   verification_status, account_status, created_at, updated_at)
VALUES ('agency-demo-7c99b9d90d', 'agency-brand', 'agency', 'Ava', 'Shah', 'Ava Shah', 'agency@pitchrooms.demo', '$2y$11$Yh.GelbLUqnsPtV91Jd0Ees4N2Ti2tQibCH/auaReThWk6PexaTmi',
        '+91 98765 43210', 'India', 'Northstar Studio', 'Creative Director', UTC_TIMESTAMP(), UTC_TIMESTAMP(),
        'Verified', 'Active', UTC_TIMESTAMP(), UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), name = VALUES(name);

INSERT INTO profiles (user_id, type, display_name, headline, bio, location, sector, stage,
                      experience, rating, reviews, trust_score, verified, payload, created_at, updated_at)
VALUES ('agency-demo-7c99b9d90d', 'agency', 'Northstar Studio', 'Creative Director', 'Ava Shah on PitchRooms.', 'India', NULL, NULL, 'Senior', 0, 0, 0, 1, '[]', UTC_TIMESTAMP(), UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE display_name = VALUES(display_name), verified = 1;

INSERT IGNORE INTO profile_skills (user_id, skill) VALUES ('agency-demo-7c99b9d90d', 'Branding');
INSERT IGNORE INTO profile_skills (user_id, skill) VALUES ('agency-demo-7c99b9d90d', 'Campaign');
INSERT IGNORE INTO profile_skills (user_id, skill) VALUES ('agency-demo-7c99b9d90d', 'Performance Marketing');
INSERT IGNORE INTO profile_skills (user_id, skill) VALUES ('agency-demo-7c99b9d90d', 'Social');

INSERT INTO users (id, panel_id, role, first_name, last_name, name, email, password_hash,
                   phone, country, company, title, email_verified_at, phone_verified_at,
                   verification_status, account_status, created_at, updated_at)
VALUES ('brand-demo-49309b3dec', 'agency-brand', 'brand', 'Noah', 'Kapoor', 'Aurora Retail', 'brand@pitchrooms.demo', '$2y$11$60c9KONSG4NmAnmzUy5ONev0f3QTdx/g7WF1v74e.6wuPrsEbzKTO',
        '+91 98765 43210', 'United States', 'Aurora Retail', 'Brand Lead', UTC_TIMESTAMP(), UTC_TIMESTAMP(),
        'Verified', 'Active', UTC_TIMESTAMP(), UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), name = VALUES(name);

INSERT INTO profiles (user_id, type, display_name, headline, bio, location, sector, stage,
                      experience, rating, reviews, trust_score, verified, payload, created_at, updated_at)
VALUES ('brand-demo-49309b3dec', 'brand', 'Aurora Retail', 'Brand Lead', 'Aurora Retail on PitchRooms.', 'United States', NULL, NULL, 'Senior', 0, 0, 0, 1, '[]', UTC_TIMESTAMP(), UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE display_name = VALUES(display_name), verified = 1;


INSERT INTO users (id, panel_id, role, first_name, last_name, name, email, password_hash,
                   phone, country, company, title, email_verified_at, phone_verified_at,
                   verification_status, account_status, created_at, updated_at)
VALUES ('employee-demo-bf636e5bcf', 'employee-employer', 'employee', 'Nishtha', 'Patel', 'Nishtha Patel', 'employee@pitchrooms.demo', '$2y$11$37RW1AolDbxSfTYsOY/LSekuWUStSXZbg618avVQPairz5qZe2EjC',
        '+91 98765 43210', 'India', NULL, 'Product Designer', UTC_TIMESTAMP(), UTC_TIMESTAMP(),
        'Verified', 'Active', UTC_TIMESTAMP(), UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), name = VALUES(name);

INSERT INTO profiles (user_id, type, display_name, headline, bio, location, sector, stage,
                      experience, rating, reviews, trust_score, verified, payload, created_at, updated_at)
VALUES ('employee-demo-bf636e5bcf', 'candidate', 'Nishtha Patel', 'Product Designer', 'Nishtha Patel on PitchRooms.', 'India', NULL, NULL, 'Senior', 0, 0, 0, 1, '[]', UTC_TIMESTAMP(), UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE display_name = VALUES(display_name), verified = 1;

INSERT IGNORE INTO profile_skills (user_id, skill) VALUES ('employee-demo-bf636e5bcf', 'Product Design');
INSERT IGNORE INTO profile_skills (user_id, skill) VALUES ('employee-demo-bf636e5bcf', 'Figma');
INSERT IGNORE INTO profile_skills (user_id, skill) VALUES ('employee-demo-bf636e5bcf', 'UX Research');
INSERT IGNORE INTO profile_skills (user_id, skill) VALUES ('employee-demo-bf636e5bcf', 'Design Systems');

INSERT INTO users (id, panel_id, role, first_name, last_name, name, email, password_hash,
                   phone, country, company, title, email_verified_at, phone_verified_at,
                   verification_status, account_status, created_at, updated_at)
VALUES ('employer-demo-79fe573578', 'employee-employer', 'employer', 'Liam', 'Mehta', 'Liam Mehta', 'employer@pitchrooms.demo', '$2y$11$qBlyomMQKR6M/ouRb1qZCuFbeNj.kvufCAAvXK1rBr9HNMLB2jxru',
        '+91 98765 43210', 'United Kingdom', 'Horizon Labs', 'Head of Talent', UTC_TIMESTAMP(), UTC_TIMESTAMP(),
        'Verified', 'Active', UTC_TIMESTAMP(), UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), name = VALUES(name);

INSERT INTO profiles (user_id, type, display_name, headline, bio, location, sector, stage,
                      experience, rating, reviews, trust_score, verified, payload, created_at, updated_at)
VALUES ('employer-demo-79fe573578', 'employer', 'Horizon Labs', 'Head of Talent', 'Liam Mehta on PitchRooms.', 'United Kingdom', NULL, NULL, 'Senior', 0, 0, 0, 1, '[]', UTC_TIMESTAMP(), UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE display_name = VALUES(display_name), verified = 1;


INSERT INTO users (id, panel_id, role, first_name, last_name, name, email, password_hash,
                   phone, country, company, title, email_verified_at, phone_verified_at,
                   verification_status, account_status, created_at, updated_at)
VALUES ('startup-demo-efd78873bf', 'startup-investor', 'startup', 'Zoe', 'Rao', 'Zoe Rao', 'startup@pitchrooms.demo', '$2y$11$v/WqU.g7VEwG8dOHj7LbROtKCLvfhrgCI37BsVIPKrfaa5gTsPq6u',
        '+91 98765 43210', 'Singapore', 'Lumen Labs', 'Founder', UTC_TIMESTAMP(), UTC_TIMESTAMP(),
        'Verified', 'Active', UTC_TIMESTAMP(), UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), name = VALUES(name);

INSERT INTO profiles (user_id, type, display_name, headline, bio, location, sector, stage,
                      experience, rating, reviews, trust_score, verified, payload, created_at, updated_at)
VALUES ('startup-demo-efd78873bf', 'startup', 'Lumen Labs', 'Founder', 'Zoe Rao on PitchRooms.', 'Singapore', 'SaaS', 'Seed', 'Senior', 0, 0, 0, 1, '{"founder":"Zoe Rao","tags":["SaaS"]}', UTC_TIMESTAMP(), UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE display_name = VALUES(display_name), verified = 1;

INSERT IGNORE INTO profile_skills (user_id, skill) VALUES ('startup-demo-efd78873bf', 'SaaS');
INSERT IGNORE INTO profile_skills (user_id, skill) VALUES ('startup-demo-efd78873bf', 'Analytics');
INSERT IGNORE INTO profile_skills (user_id, skill) VALUES ('startup-demo-efd78873bf', 'B2B');

INSERT INTO users (id, panel_id, role, first_name, last_name, name, email, password_hash,
                   phone, country, company, title, email_verified_at, phone_verified_at,
                   verification_status, account_status, created_at, updated_at)
VALUES ('investor-demo-977d6c6674', 'startup-investor', 'investor', 'Ethan', 'Iyer', 'Ethan Iyer', 'investor@pitchrooms.demo', '$2y$11$RGfI9Hah.p8iC.zXOWJdwet01FHdLiL6o5w4AMgrpqxVHDa6eHRIC',
        '+91 98765 43210', 'United Arab Emirates', 'Northwind Capital', 'Partner', UTC_TIMESTAMP(), UTC_TIMESTAMP(),
        'Verified', 'Active', UTC_TIMESTAMP(), UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), name = VALUES(name);

INSERT INTO profiles (user_id, type, display_name, headline, bio, location, sector, stage,
                      experience, rating, reviews, trust_score, verified, payload, created_at, updated_at)
VALUES ('investor-demo-977d6c6674', 'investor', 'Northwind Capital', 'Partner', 'Ethan Iyer on PitchRooms.', 'United Arab Emirates', 'SaaS', NULL, 'Senior', 0, 0, 0, 1, '{"firm":"Northwind Capital","investorType":"VC firm"}', UTC_TIMESTAMP(), UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE display_name = VALUES(display_name), verified = 1;


INSERT INTO users (id, panel_id, role, first_name, last_name, name, email, password_hash,
                   phone, country, company, title, email_verified_at, phone_verified_at,
                   verification_status, account_status, created_at, updated_at)
VALUES ('admin-demo-42dc47bd3b', 'internal', 'admin', 'Priya', 'Nair', 'Priya Nair', 'admin@pitchrooms.demo', '$2y$11$XcBwJGc2hb.ArKOW8nsjd.2A7ejtz5I2d0X8bpycM6Z/2HXmJCFsO',
        '+91 98765 43210', 'India', 'PitchRooms', 'Platform Admin', UTC_TIMESTAMP(), UTC_TIMESTAMP(),
        'Verified', 'Active', UTC_TIMESTAMP(), UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), name = VALUES(name);

INSERT INTO profiles (user_id, type, display_name, headline, bio, location, sector, stage,
                      experience, rating, reviews, trust_score, verified, payload, created_at, updated_at)
VALUES ('admin-demo-42dc47bd3b', 'agency', 'PitchRooms', 'Platform Admin', 'Priya Nair on PitchRooms.', 'India', NULL, NULL, 'Senior', 0, 0, 0, 1, '[]', UTC_TIMESTAMP(), UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE display_name = VALUES(display_name), verified = 1;

