-- ===========================================================================
-- PitchRooms — full schema installer
-- Generated by bin/build-installer.php on 2026-09-24 08:50:34 UTC
--
-- phpMyAdmin: select your database, open Import, choose this file, Go.
-- Safe to re-run: every statement is CREATE TABLE IF NOT EXISTS or an
-- INSERT ... ON DUPLICATE KEY UPDATE.
-- ===========================================================================

SET NAMES utf8mb4;
SET time_zone = "+00:00";
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS migrations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(190) NOT NULL UNIQUE,
    applied_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- 001_core.sql
-- ---------------------------------------------------------------------------

-- ===========================================================================
-- 001_core — users, profiles, auth, files, audit
-- ===========================================================================

CREATE TABLE IF NOT EXISTS users (
    id                  VARCHAR(64)  NOT NULL PRIMARY KEY,
    panel_id            VARCHAR(32)  NOT NULL,
    role                VARCHAR(24)  NOT NULL,
    first_name          VARCHAR(80)  NULL,
    last_name           VARCHAR(80)  NULL,
    name                VARCHAR(160) NOT NULL,
    email               VARCHAR(190) NOT NULL,
    password_hash       VARCHAR(255) NOT NULL,
    phone               VARCHAR(32)  NULL,
    country             VARCHAR(80)  NULL,
    company             VARCHAR(160) NULL,
    title               VARCHAR(120) NULL,
    avatar_file_id      VARCHAR(64)  NULL,
    email_verified_at   DATETIME     NULL,
    phone_verified_at   DATETIME     NULL,
    verification_status VARCHAR(24)  NOT NULL DEFAULT 'Pending',
    account_status      VARCHAR(24)  NOT NULL DEFAULT 'Active',
    last_login_at       DATETIME     NULL,
    created_at          DATETIME     NOT NULL,
    updated_at          DATETIME     NOT NULL,
    deleted_at          DATETIME     NULL,
    UNIQUE KEY uq_users_email (email),
    KEY idx_users_role (role, account_status),
    KEY idx_users_panel (panel_id, role),
    KEY idx_users_verification (verification_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- One profile row per user. `payload` holds the role-specific shape the
-- frontend already renders; the indexed columns are the ones we filter on.
CREATE TABLE IF NOT EXISTS profiles (
    user_id      VARCHAR(64)  NOT NULL PRIMARY KEY,
    type         VARCHAR(24)  NOT NULL,
    display_name VARCHAR(160) NULL,
    headline     VARCHAR(255) NULL,
    bio          TEXT         NULL,
    location     VARCHAR(160) NULL,
    website      VARCHAR(255) NULL,
    linkedin     VARCHAR(255) NULL,
    logo_file_id VARCHAR(64)  NULL,
    sector       VARCHAR(80)  NULL,
    stage        VARCHAR(80)  NULL,
    specialty    VARCHAR(160) NULL,
    experience   VARCHAR(80)  NULL,
    rating       DECIMAL(3,2) NOT NULL DEFAULT 0.00,
    reviews      INT          NOT NULL DEFAULT 0,
    trust_score  INT          NOT NULL DEFAULT 0,
    verified     TINYINT(1)   NOT NULL DEFAULT 0,
    payload      JSON         NULL,
    created_at   DATETIME     NOT NULL,
    updated_at   DATETIME     NOT NULL,
    KEY idx_profiles_type (type),
    KEY idx_profiles_sector (sector, stage),
    CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS profile_skills (
    user_id VARCHAR(64) NOT NULL,
    skill   VARCHAR(80) NOT NULL,
    PRIMARY KEY (user_id, skill),
    KEY idx_profile_skills_skill (skill),
    CONSTRAINT fk_profile_skills_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id         VARCHAR(64)  NOT NULL PRIMARY KEY,
    user_id    VARCHAR(64)  NOT NULL,
    token_hash CHAR(64)     NOT NULL,
    user_agent VARCHAR(255) NULL,
    ip         VARCHAR(64)  NULL,
    expires_at DATETIME     NOT NULL,
    revoked_at DATETIME     NULL,
    created_at DATETIME     NOT NULL,
    UNIQUE KEY uq_refresh_hash (token_hash),
    KEY idx_refresh_user (user_id, revoked_at),
    CONSTRAINT fk_refresh_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS otp_codes (
    id          VARCHAR(64)  NOT NULL PRIMARY KEY,
    user_id     VARCHAR(64)  NULL,
    destination VARCHAR(190) NOT NULL,
    channel     VARCHAR(16)  NOT NULL,
    purpose     VARCHAR(40)  NOT NULL,
    entity_id   VARCHAR(64)  NULL,
    code_hash   CHAR(64)     NOT NULL,
    attempts    INT          NOT NULL DEFAULT 0,
    expires_at  DATETIME     NOT NULL,
    consumed_at DATETIME     NULL,
    created_at  DATETIME     NOT NULL,
    KEY idx_otp_lookup (destination, purpose, consumed_at),
    KEY idx_otp_user (user_id, purpose)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS password_resets (
    id         VARCHAR(64)  NOT NULL PRIMARY KEY,
    user_id    VARCHAR(64)  NOT NULL,
    token_hash CHAR(64)     NOT NULL,
    expires_at DATETIME     NOT NULL,
    used_at    DATETIME     NULL,
    created_at DATETIME     NOT NULL,
    UNIQUE KEY uq_reset_hash (token_hash),
    CONSTRAINT fk_reset_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS files (
    id           VARCHAR(64)  NOT NULL PRIMARY KEY,
    owner_id     VARCHAR(64)  NULL,
    kind         VARCHAR(40)  NOT NULL DEFAULT 'document',
    name         VARCHAR(255) NOT NULL,
    mime_type    VARCHAR(120) NOT NULL,
    size_bytes   BIGINT       NOT NULL DEFAULT 0,
    storage_path VARCHAR(255) NOT NULL,
    checksum     CHAR(64)     NULL,
    visibility   VARCHAR(16)  NOT NULL DEFAULT 'private',
    created_at   DATETIME     NOT NULL,
    deleted_at   DATETIME     NULL,
    KEY idx_files_owner (owner_id, kind)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS activity_log (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    actor_id    VARCHAR(64)  NULL,
    entity_type VARCHAR(40)  NOT NULL,
    entity_id   VARCHAR(64)  NULL,
    action      VARCHAR(60)  NOT NULL,
    diff        JSON         NULL,
    ip          VARCHAR(64)  NULL,
    user_agent  VARCHAR(255) NULL,
    created_at  DATETIME     NOT NULL,
    KEY idx_activity_entity (entity_type, entity_id, created_at),
    KEY idx_activity_actor (actor_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rate_limits (
    bucket      VARCHAR(190) NOT NULL PRIMARY KEY,
    hits        INT          NOT NULL DEFAULT 0,
    window_started_at DATETIME NOT NULL,
    updated_at  DATETIME     NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settings (
    `key`      VARCHAR(120) NOT NULL PRIMARY KEY,
    value      JSON         NULL,
    updated_at DATETIME     NOT NULL,
    updated_by VARCHAR(64)  NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO migrations (filename, applied_at) VALUES ('001_core.sql', UTC_TIMESTAMP())
    ON DUPLICATE KEY UPDATE applied_at = applied_at;

-- ---------------------------------------------------------------------------
-- 002_marketplace.sql
-- ---------------------------------------------------------------------------

-- ===========================================================================
-- 002_marketplace — opportunities, proposals, shortlists, invitations
-- One schema for all three verticals; `vertical` is the discriminator:
--   ab = brief (brand -> agency), ee = job (employer -> candidate),
--   si = raise (startup -> investor)
-- ===========================================================================

CREATE TABLE IF NOT EXISTS opportunities (
    id                    VARCHAR(64)  NOT NULL PRIMARY KEY,
    vertical              VARCHAR(8)   NOT NULL,
    owner_id              VARCHAR(64)  NOT NULL,
    owner_name            VARCHAR(160) NULL,
    company               VARCHAR(160) NULL,
    title                 VARCHAR(255) NOT NULL,
    category              VARCHAR(120) NULL,
    subcategory           VARCHAR(120) NULL,
    industry              VARCHAR(120) NULL,
    description           TEXT         NULL,
    requirements          TEXT         NULL,
    benefits              TEXT         NULL,
    budget                VARCHAR(80)  NULL,
    budget_type           VARCHAR(60)  NULL,
    duration              VARCHAR(80)  NULL,
    location              VARCHAR(160) NULL,
    work_type             VARCHAR(60)  NULL,
    experience            VARCHAR(80)  NULL,
    department            VARCHAR(120) NULL,
    job_type              VARCHAR(60)  NULL,
    openings              INT          NOT NULL DEFAULT 1,
    deadline              DATETIME     NULL,
    expected_start_date   DATETIME     NULL,
    preferred_sellers     VARCHAR(24)  NOT NULL DEFAULT 'Top 5',
    presentation_duration INT          NOT NULL DEFAULT 30,
    qa_duration           INT          NOT NULL DEFAULT 30,
    visibility            VARCHAR(24)  NOT NULL DEFAULT 'open',
    featured              TINYINT(1)   NOT NULL DEFAULT 0,
    cover_file_id         VARCHAR(64)  NULL,
    cover_url             VARCHAR(500) NULL,
    -- SI-only fields
    round                 VARCHAR(60)  NULL,
    amount                VARCHAR(80)  NULL,
    valuation             VARCHAR(80)  NULL,
    stage                 VARCHAR(60)  NULL,
    use_of_funds          TEXT         NULL,
    deck_file_id          VARCHAR(64)  NULL,
    status                VARCHAR(40)  NOT NULL DEFAULT 'Draft',
    event_id              VARCHAR(64)  NULL,
    created_at            DATETIME     NOT NULL,
    updated_at            DATETIME     NOT NULL,
    deleted_at            DATETIME     NULL,
    KEY idx_opp_listing (vertical, status, created_at),
    KEY idx_opp_owner (owner_id, status),
    KEY idx_opp_category (category, subcategory),
    KEY idx_opp_deadline (deadline),
    CONSTRAINT fk_opp_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS opportunity_skills (
    opportunity_id VARCHAR(64) NOT NULL,
    skill          VARCHAR(80) NOT NULL,
    PRIMARY KEY (opportunity_id, skill),
    KEY idx_opp_skill (skill),
    CONSTRAINT fk_opp_skill FOREIGN KEY (opportunity_id) REFERENCES opportunities (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS opportunity_files (
    opportunity_id VARCHAR(64) NOT NULL,
    file_id        VARCHAR(64) NOT NULL,
    kind           VARCHAR(40) NOT NULL DEFAULT 'attachment',
    PRIMARY KEY (opportunity_id, file_id),
    CONSTRAINT fk_oppfile_opp FOREIGN KEY (opportunity_id) REFERENCES opportunities (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS opportunity_timeline (
    id             BIGINT AUTO_INCREMENT PRIMARY KEY,
    opportunity_id VARCHAR(64) NOT NULL,
    stage          VARCHAR(60) NOT NULL,
    note           VARCHAR(500) NULL,
    actor_id       VARCHAR(64) NULL,
    at             DATETIME    NOT NULL,
    KEY idx_opp_timeline (opportunity_id, at),
    CONSTRAINT fk_opp_timeline FOREIGN KEY (opportunity_id) REFERENCES opportunities (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- pitch (ab) / application (ee) / interest (si)
CREATE TABLE IF NOT EXISTS proposals (
    id              VARCHAR(64)  NOT NULL PRIMARY KEY,
    opportunity_id  VARCHAR(64)  NOT NULL,
    vertical        VARCHAR(8)   NOT NULL,
    seller_id       VARCHAR(64)  NOT NULL,
    buyer_id        VARCHAR(64)  NOT NULL,
    seller_name     VARCHAR(160) NULL,
    company         VARCHAR(160) NULL,
    cover_letter    TEXT         NULL,
    bid             VARCHAR(80)  NULL,
    timeline_text   VARCHAR(120) NULL,
    expected_salary VARCHAR(80)  NULL,
    notice_period   VARCHAR(80)  NULL,
    resume_file_id  VARCHAR(64)  NULL,
    deck_file_id    VARCHAR(64)  NULL,
    note            VARCHAR(500) NULL,
    match_score     INT          NULL,
    status          VARCHAR(40)  NOT NULL DEFAULT 'submitted',
    rejection_reason VARCHAR(500) NULL,
    event_id        VARCHAR(64)  NULL,
    created_at      DATETIME     NOT NULL,
    updated_at      DATETIME     NOT NULL,
    UNIQUE KEY uq_proposal_seller (opportunity_id, seller_id),
    KEY idx_proposal_status (opportunity_id, status),
    KEY idx_proposal_seller (seller_id, status),
    KEY idx_proposal_buyer (buyer_id, status),
    CONSTRAINT fk_proposal_opp FOREIGN KEY (opportunity_id) REFERENCES opportunities (id) ON DELETE CASCADE,
    CONSTRAINT fk_proposal_seller FOREIGN KEY (seller_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS proposal_timeline (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    proposal_id VARCHAR(64)  NOT NULL,
    stage       VARCHAR(60)  NOT NULL,
    note        VARCHAR(500) NULL,
    actor_id    VARCHAR(64)  NULL,
    at          DATETIME     NOT NULL,
    KEY idx_proposal_timeline (proposal_id, at),
    CONSTRAINT fk_proposal_timeline FOREIGN KEY (proposal_id) REFERENCES proposals (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS shortlists (
    opportunity_id VARCHAR(64) NOT NULL,
    seller_id      VARCHAR(64) NOT NULL,
    proposal_id    VARCHAR(64) NULL,
    position       INT         NULL,
    match_score    INT         NULL,
    locked_at      DATETIME    NULL,
    created_by     VARCHAR(64) NULL,
    created_at     DATETIME    NOT NULL,
    PRIMARY KEY (opportunity_id, seller_id),
    KEY idx_shortlist_seller (seller_id),
    CONSTRAINT fk_shortlist_opp FOREIGN KEY (opportunity_id) REFERENCES opportunities (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Investor/buyer watchlist — the "save for later" shortlist, distinct from
-- the binding event shortlist above.
CREATE TABLE IF NOT EXISTS watchlists (
    user_id        VARCHAR(64) NOT NULL,
    opportunity_id VARCHAR(64) NOT NULL,
    note           VARCHAR(500) NULL,
    created_at     DATETIME    NOT NULL,
    PRIMARY KEY (user_id, opportunity_id),
    CONSTRAINT fk_watchlist_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_watchlist_opp FOREIGN KEY (opportunity_id) REFERENCES opportunities (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invitations (
    id             VARCHAR(64)  NOT NULL PRIMARY KEY,
    opportunity_id VARCHAR(64)  NOT NULL,
    event_id       VARCHAR(64)  NULL,
    seller_id      VARCHAR(64)  NOT NULL,
    buyer_id       VARCHAR(64)  NOT NULL,
    proposal_id    VARCHAR(64)  NULL,
    status         VARCHAR(40)  NOT NULL DEFAULT 'Sent',
    rsvp_status    VARCHAR(40)  NOT NULL DEFAULT 'Pending',
    selected_position INT       NULL,
    message        VARCHAR(1000) NULL,
    responded_at   DATETIME     NULL,
    created_at     DATETIME     NOT NULL,
    updated_at     DATETIME     NOT NULL,
    UNIQUE KEY uq_invitation (opportunity_id, seller_id),
    KEY idx_invitation_seller (seller_id, status),
    CONSTRAINT fk_invitation_opp FOREIGN KEY (opportunity_id) REFERENCES opportunities (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO migrations (filename, applied_at) VALUES ('002_marketplace.sql', UTC_TIMESTAMP())
    ON DUPLICATE KEY UPDATE applied_at = applied_at;

-- ---------------------------------------------------------------------------
-- 003_meetings.sql
-- ---------------------------------------------------------------------------

-- ===========================================================================
-- 003_meetings — pitch events, the live room, entry gate, evaluation, decisions
-- ===========================================================================

CREATE TABLE IF NOT EXISTS events (
    id                    VARCHAR(64)  NOT NULL PRIMARY KEY,
    opportunity_id        VARCHAR(64)  NULL,
    vertical              VARCHAR(8)   NOT NULL,
    buyer_id              VARCHAR(64)  NOT NULL,
    seller_id             VARCHAR(64)  NULL,       -- 1:1 meetings (EE interview, SI pitch)
    proposal_id           VARCHAR(64)  NULL,
    name                  VARCHAR(255) NOT NULL,
    agenda                TEXT         NULL,
    status                VARCHAR(32)  NOT NULL DEFAULT 'requested',
    start_at              DATETIME     NULL,
    end_at                DATETIME     NULL,
    presentation_duration INT          NOT NULL DEFAULT 30,
    qa_duration           INT          NOT NULL DEFAULT 30,
    room_name             VARCHAR(120) NOT NULL,
    meeting_code          VARCHAR(12)  NOT NULL,
    created_by            VARCHAR(64)  NOT NULL,
    accepted_by           VARCHAR(64)  NULL,
    accepted_at           DATETIME     NULL,
    started_at            DATETIME     NULL,
    ended_at              DATETIME     NULL,
    cancelled_at          DATETIME     NULL,
    cancel_reason         VARCHAR(500) NULL,
    decision              VARCHAR(40)  NULL,
    recording_file_id     VARCHAR(64)  NULL,
    created_at            DATETIME     NOT NULL,
    updated_at            DATETIME     NOT NULL,
    UNIQUE KEY uq_event_room (room_name),
    KEY idx_event_schedule (status, start_at),
    KEY idx_event_buyer (buyer_id, status),
    KEY idx_event_seller (seller_id, status),
    KEY idx_event_opp (opportunity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS event_participants (
    event_id           VARCHAR(64) NOT NULL,
    user_id            VARCHAR(64) NOT NULL,
    role               VARCHAR(24) NOT NULL,
    side               VARCHAR(12) NOT NULL DEFAULT 'seller',  -- buyer | seller | observer
    slot_position      INT         NULL,
    fee_minor          BIGINT      NOT NULL DEFAULT 0,
    currency           VARCHAR(8)  NULL,
    rsvp_status        VARCHAR(24) NOT NULL DEFAULT 'Pending',
    joined_at          DATETIME    NULL,
    left_at            DATETIME    NULL,
    attendance_seconds INT         NOT NULL DEFAULT 0,
    created_at         DATETIME    NOT NULL,
    PRIMARY KEY (event_id, user_id),
    KEY idx_participant_user (user_id),
    UNIQUE KEY uq_event_slot (event_id, slot_position),
    CONSTRAINT fk_participant_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS event_agenda (
    id                   VARCHAR(64)  NOT NULL PRIMARY KEY,
    event_id             VARCHAR(64)  NOT NULL,
    position             INT          NOT NULL,
    seller_id            VARCHAR(64)  NULL,
    title                VARCHAR(255) NOT NULL,
    type                 VARCHAR(24)  NOT NULL DEFAULT 'seller',
    presentation_seconds INT          NOT NULL DEFAULT 30,
    qa_seconds           INT          NOT NULL DEFAULT 30,
    is_premium           TINYINT(1)   NOT NULL DEFAULT 0,
    fee_minor            BIGINT       NOT NULL DEFAULT 0,
    UNIQUE KEY uq_agenda_position (event_id, position),
    CONSTRAINT fk_agenda_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Server-authoritative room clock. Clients render from this, not from their
-- own setInterval, so every participant sees the same countdown.
CREATE TABLE IF NOT EXISTS meeting_state (
    event_id        VARCHAR(64) NOT NULL PRIMARY KEY,
    stage           VARCHAR(24) NOT NULL DEFAULT 'waiting',
    presenter_index INT         NOT NULL DEFAULT 0,
    presenter_id    VARCHAR(64) NULL,
    stage_started_at DATETIME   NULL,
    stage_ends_at   DATETIME    NULL,
    paused_at       DATETIME    NULL,
    updated_at      DATETIME    NOT NULL,
    CONSTRAINT fk_state_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meeting_access (
    id                 VARCHAR(64)  NOT NULL PRIMARY KEY,
    event_id           VARCHAR(64)  NOT NULL,
    user_id            VARCHAR(64)  NOT NULL,
    code_ok            TINYINT(1)   NOT NULL DEFAULT 0,
    email_otp_ok       TINYINT(1)   NOT NULL DEFAULT 0,
    mobile_otp_ok      TINYINT(1)   NOT NULL DEFAULT 0,
    camera_ok          TINYINT(1)   NOT NULL DEFAULT 0,
    device_fingerprint VARCHAR(120) NULL,
    ip                 VARCHAR(64)  NULL,
    granted_at         DATETIME     NULL,
    expires_at         DATETIME     NULL,
    revoked_at         DATETIME     NULL,
    revoke_reason      VARCHAR(255) NULL,
    created_at         DATETIME     NOT NULL,
    updated_at         DATETIME     NOT NULL,
    UNIQUE KEY uq_access (event_id, user_id),
    CONSTRAINT fk_access_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meeting_messages (
    id         VARCHAR(64)  NOT NULL PRIMARY KEY,
    event_id   VARCHAR(64)  NOT NULL,
    from_id    VARCHAR(64)  NULL,
    sender     VARCHAR(160) NULL,
    sender_role VARCHAR(24) NULL,
    body       TEXT         NOT NULL,
    type       VARCHAR(16)  NOT NULL DEFAULT 'user',
    created_at DATETIME     NOT NULL,
    KEY idx_room_chat (event_id, created_at),
    CONSTRAINT fk_roomchat_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meeting_questions (
    id           VARCHAR(64)  NOT NULL PRIMARY KEY,
    event_id     VARCHAR(64)  NOT NULL,
    asked_by     VARCHAR(64)  NOT NULL,
    asker_name   VARCHAR(160) NULL,
    presenter_id VARCHAR(64)  NULL,
    category     VARCHAR(60)  NULL,
    question     VARCHAR(1000) NOT NULL,
    answer       TEXT         NULL,
    answered_by  VARCHAR(64)  NULL,
    answered_at  DATETIME     NULL,
    upvotes      INT          NOT NULL DEFAULT 0,
    created_at   DATETIME     NOT NULL,
    KEY idx_question_event (event_id, created_at),
    CONSTRAINT fk_question_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meeting_question_votes (
    question_id VARCHAR(64) NOT NULL,
    user_id     VARCHAR(64) NOT NULL,
    created_at  DATETIME    NOT NULL,
    PRIMARY KEY (question_id, user_id),
    CONSTRAINT fk_qvote_question FOREIGN KEY (question_id) REFERENCES meeting_questions (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS evaluations (
    id                 VARCHAR(64) NOT NULL PRIMARY KEY,
    event_id           VARCHAR(64) NOT NULL,
    evaluator_id       VARCHAR(64) NOT NULL,
    seller_id          VARCHAR(64) NOT NULL,
    industry_expertise TINYINT     NOT NULL DEFAULT 0,
    creativity         TINYINT     NOT NULL DEFAULT 0,
    team_confidence    TINYINT     NOT NULL DEFAULT 0,
    communication      TINYINT     NOT NULL DEFAULT 0,
    case_studies       TINYINT     NOT NULL DEFAULT 0,
    commercial_fit     TINYINT     NOT NULL DEFAULT 0,
    total_score        DECIMAL(5,2) NOT NULL DEFAULT 0,
    notes              TEXT        NULL,
    submitted_at       DATETIME    NOT NULL,
    UNIQUE KEY uq_evaluation (event_id, evaluator_id, seller_id),
    KEY idx_evaluation_seller (event_id, seller_id),
    CONSTRAINT fk_evaluation_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS decisions (
    id           VARCHAR(64)  NOT NULL PRIMARY KEY,
    event_id     VARCHAR(64)  NOT NULL,
    opportunity_id VARCHAR(64) NULL,
    winner_id    VARCHAR(64)  NULL,
    outcome      VARCHAR(40)  NOT NULL,
    backup_ids   JSON         NULL,
    note         TEXT         NULL,
    created_by   VARCHAR(64)  NOT NULL,
    published_at DATETIME     NULL,
    created_at   DATETIME     NOT NULL,
    UNIQUE KEY uq_decision_event (event_id),
    CONSTRAINT fk_decision_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS follow_ups (
    id         VARCHAR(64)  NOT NULL PRIMARY KEY,
    event_id   VARCHAR(64)  NOT NULL,
    seller_id  VARCHAR(64)  NULL,
    scheduled_at DATETIME   NULL,
    notes      TEXT         NULL,
    created_by VARCHAR(64)  NOT NULL,
    created_at DATETIME     NOT NULL,
    KEY idx_followup_event (event_id),
    CONSTRAINT fk_followup_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS investments (
    id           VARCHAR(64)  NOT NULL PRIMARY KEY,
    event_id     VARCHAR(64)  NULL,
    opportunity_id VARCHAR(64) NULL,
    investor_id  VARCHAR(64)  NOT NULL,
    startup_id   VARCHAR(64)  NOT NULL,
    amount_minor BIGINT       NOT NULL DEFAULT 0,
    currency     VARCHAR(8)   NOT NULL DEFAULT 'USD',
    instrument   VARCHAR(60)  NULL,
    terms        TEXT         NULL,
    status       VARCHAR(40)  NOT NULL DEFAULT 'Decision Pending',
    created_at   DATETIME     NOT NULL,
    updated_at   DATETIME     NOT NULL,
    KEY idx_investment_investor (investor_id, status),
    KEY idx_investment_startup (startup_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ratings (
    id         VARCHAR(64) NOT NULL PRIMARY KEY,
    from_id    VARCHAR(64) NOT NULL,
    to_id      VARCHAR(64) NOT NULL,
    event_id   VARCHAR(64) NULL,
    opportunity_id VARCHAR(64) NULL,
    score      DECIMAL(3,2) NOT NULL,
    comment    TEXT        NULL,
    created_at DATETIME    NOT NULL,
    KEY idx_rating_to (to_id, created_at),
    UNIQUE KEY uq_rating (from_id, to_id, event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS feedback (
    id         VARCHAR(64) NOT NULL PRIMARY KEY,
    event_id   VARCHAR(64) NULL,
    seller_id  VARCHAR(64) NOT NULL,
    buyer_id   VARCHAR(64) NOT NULL,
    body       TEXT        NOT NULL,
    strengths  TEXT        NULL,
    improvements TEXT      NULL,
    visibility VARCHAR(16) NOT NULL DEFAULT 'seller',
    created_at DATETIME    NOT NULL,
    KEY idx_feedback_seller (seller_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO migrations (filename, applied_at) VALUES ('003_meetings.sql', UTC_TIMESTAMP())
    ON DUPLICATE KEY UPDATE applied_at = applied_at;

-- ---------------------------------------------------------------------------
-- 004_messaging_billing_jobs.sql
-- ---------------------------------------------------------------------------

-- ===========================================================================
-- 004 — messaging, notifications, billing, and the in-code job scheduler
-- ===========================================================================

CREATE TABLE IF NOT EXISTS threads (
    id                   VARCHAR(64) NOT NULL PRIMARY KEY,
    vertical             VARCHAR(8)  NOT NULL,
    party_a_id           VARCHAR(64) NOT NULL,   -- always the lexicographically smaller id
    party_b_id           VARCHAR(64) NOT NULL,
    opportunity_id       VARCHAR(64) NULL,
    unlocked_by_event_id VARCHAR(64) NULL,
    last_message_at      DATETIME    NULL,
    last_message_preview VARCHAR(255) NULL,
    archived_by          JSON        NULL,
    muted_by             JSON        NULL,
    created_at           DATETIME    NOT NULL,
    UNIQUE KEY uq_thread_pair (party_a_id, party_b_id, opportunity_id),
    KEY idx_thread_a (party_a_id, last_message_at),
    KEY idx_thread_b (party_b_id, last_message_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS messages (
    id            VARCHAR(64) NOT NULL PRIMARY KEY,
    thread_id     VARCHAR(64) NOT NULL,
    from_id       VARCHAR(64) NULL,
    to_id         VARCHAR(64) NULL,
    body          TEXT        NOT NULL,
    type          VARCHAR(16) NOT NULL DEFAULT 'user',
    client_msg_id VARCHAR(80) NULL,
    read_at       DATETIME    NULL,
    created_at    DATETIME    NOT NULL,
    UNIQUE KEY uq_client_msg (thread_id, client_msg_id),
    KEY idx_message_thread (thread_id, created_at),
    KEY idx_message_unread (to_id, read_at),
    CONSTRAINT fk_message_thread FOREIGN KEY (thread_id) REFERENCES threads (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS message_attachments (
    message_id VARCHAR(64) NOT NULL,
    file_id    VARCHAR(64) NOT NULL,
    PRIMARY KEY (message_id, file_id),
    CONSTRAINT fk_attachment_message FOREIGN KEY (message_id) REFERENCES messages (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notifications (
    id           VARCHAR(64)  NOT NULL PRIMARY KEY,
    user_id      VARCHAR(64)  NOT NULL,
    role         VARCHAR(24)  NULL,
    type         VARCHAR(40)  NOT NULL,
    title        VARCHAR(255) NOT NULL,
    body         VARCHAR(1000) NULL,
    link         VARCHAR(500) NULL,
    action_label VARCHAR(80)  NULL,
    entity_type  VARCHAR(40)  NULL,
    entity_id    VARCHAR(64)  NULL,
    read_at      DATETIME     NULL,
    created_at   DATETIME     NOT NULL,
    KEY idx_notification_user (user_id, read_at, created_at),
    KEY idx_notification_type (user_id, type),
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notification_preferences (
    user_id VARCHAR(64) NOT NULL,
    type    VARCHAR(40) NOT NULL,
    email   TINYINT(1)  NOT NULL DEFAULT 1,
    sms     TINYINT(1)  NOT NULL DEFAULT 0,
    in_app  TINYINT(1)  NOT NULL DEFAULT 1,
    PRIMARY KEY (user_id, type),
    CONSTRAINT fk_notifpref_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------------------------
-- Billing
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS plans (
    id            VARCHAR(40)  NOT NULL PRIMARY KEY,
    name          VARCHAR(120) NOT NULL,
    tag           VARCHAR(80)  NULL,
    badge         VARCHAR(80)  NULL,
    description   VARCHAR(500) NULL,
    price_minor   BIGINT       NOT NULL,
    currency      VARCHAR(8)   NOT NULL DEFAULT 'USD',
    period        VARCHAR(40)  NULL,
    duration_days INT          NOT NULL DEFAULT 30,
    unlimited     TINYINT(1)   NOT NULL DEFAULT 0,
    features      JSON         NULL,
    active        TINYINT(1)   NOT NULL DEFAULT 1,
    sort_order    INT          NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS passes (
    id           VARCHAR(64)  NOT NULL PRIMARY KEY,
    user_id      VARCHAR(64)  NOT NULL,
    plan_id      VARCHAR(40)  NOT NULL,
    payment_id   VARCHAR(64)  NULL,
    status       VARCHAR(24)  NOT NULL DEFAULT 'pending',
    price_minor  BIGINT       NOT NULL DEFAULT 0,
    currency     VARCHAR(8)   NOT NULL DEFAULT 'USD',
    unlimited    TINYINT(1)   NOT NULL DEFAULT 0,
    purchased_at DATETIME     NULL,
    expires_at   DATETIME     NULL,
    cancelled_at DATETIME     NULL,
    created_at   DATETIME     NOT NULL,
    KEY idx_pass_user (user_id, status, expires_at),
    CONSTRAINT fk_pass_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pass_events (
    pass_id  VARCHAR(64) NOT NULL,
    event_id VARCHAR(64) NOT NULL,
    PRIMARY KEY (pass_id, event_id),
    CONSTRAINT fk_passevent_pass FOREIGN KEY (pass_id) REFERENCES passes (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS slot_pricing (
    vertical   VARCHAR(8)   NOT NULL,
    position   INT          NOT NULL,
    title      VARCHAR(120) NOT NULL,
    description VARCHAR(500) NULL,
    fee_minor  BIGINT       NOT NULL DEFAULT 0,
    currency   VARCHAR(8)   NOT NULL DEFAULT 'INR',
    active     TINYINT(1)   NOT NULL DEFAULT 1,
    PRIMARY KEY (vertical, position)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payments (
    id           VARCHAR(64)  NOT NULL PRIMARY KEY,
    user_id      VARCHAR(64)  NOT NULL,
    provider     VARCHAR(40)  NOT NULL DEFAULT 'manual',
    provider_ref VARCHAR(190) NULL,
    kind         VARCHAR(40)  NOT NULL,          -- pass | slot
    plan_id      VARCHAR(40)  NULL,
    event_id     VARCHAR(64)  NULL,
    slot_position INT         NULL,
    amount_minor BIGINT       NOT NULL,
    currency     VARCHAR(8)   NOT NULL DEFAULT 'USD',
    status       VARCHAR(24)  NOT NULL DEFAULT 'created',
    metadata     JSON         NULL,
    created_at   DATETIME     NOT NULL,
    updated_at   DATETIME     NOT NULL,
    UNIQUE KEY uq_payment_provider_ref (provider, provider_ref),
    KEY idx_payment_user (user_id, status),
    CONSTRAINT fk_payment_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS receipts (
    id             VARCHAR(64)  NOT NULL PRIMARY KEY,
    payment_id     VARCHAR(64)  NOT NULL,
    user_id        VARCHAR(64)  NOT NULL,
    receipt_number VARCHAR(60)  NOT NULL,
    description    VARCHAR(255) NULL,
    amount_minor   BIGINT       NOT NULL,
    tax_minor      BIGINT       NOT NULL DEFAULT 0,
    total_minor    BIGINT       NOT NULL,
    currency       VARCHAR(8)   NOT NULL DEFAULT 'USD',
    issued_at      DATETIME     NOT NULL,
    pdf_file_id    VARCHAR(64)  NULL,
    UNIQUE KEY uq_receipt_number (receipt_number),
    KEY idx_receipt_user (user_id, issued_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------------------------
-- Scheduler — cron lives in code, not in the hosting panel.
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS scheduled_jobs (
    id            VARCHAR(64)  NOT NULL PRIMARY KEY,
    handler       VARCHAR(80)  NOT NULL,
    payload       JSON         NULL,
    unique_key    VARCHAR(190) NULL,
    run_at        DATETIME     NOT NULL,
    status        VARCHAR(16)  NOT NULL DEFAULT 'pending',
    attempts      INT          NOT NULL DEFAULT 0,
    max_attempts  INT          NOT NULL DEFAULT 3,
    locked_at     DATETIME     NULL,
    locked_by     VARCHAR(64)  NULL,
    last_error    VARCHAR(1000) NULL,
    completed_at  DATETIME     NULL,
    created_at    DATETIME     NOT NULL,
    UNIQUE KEY uq_job_unique (unique_key),
    KEY idx_job_due (status, run_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Recurring definitions, evaluated on every tick.
CREATE TABLE IF NOT EXISTS scheduled_tasks (
    id                VARCHAR(64)  NOT NULL PRIMARY KEY,
    handler           VARCHAR(80)  NOT NULL,
    description       VARCHAR(255) NULL,
    interval_seconds  INT          NOT NULL DEFAULT 300,
    payload           JSON         NULL,
    enabled           TINYINT(1)   NOT NULL DEFAULT 1,
    last_run_at       DATETIME     NULL,
    next_run_at       DATETIME     NULL,
    last_status       VARCHAR(24)  NULL,
    last_error        VARCHAR(1000) NULL,
    runs              INT          NOT NULL DEFAULT 0,
    KEY idx_task_due (enabled, next_run_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Single row that throttles inline ticks across concurrent requests.
CREATE TABLE IF NOT EXISTS scheduler_locks (
    name        VARCHAR(60) NOT NULL PRIMARY KEY,
    locked_at   DATETIME    NULL,
    locked_by   VARCHAR(64) NULL,
    last_tick_at DATETIME   NULL,
    ticks       BIGINT      NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO migrations (filename, applied_at) VALUES ('004_messaging_billing_jobs.sql', UTC_TIMESTAMP())
    ON DUPLICATE KEY UPDATE applied_at = applied_at;

-- ---------------------------------------------------------------------------
-- 005_seed_reference.sql
-- ---------------------------------------------------------------------------

-- ===========================================================================
-- 005 — reference data that the frontend currently hardcodes in its bundle.
-- Pricing lives here so it can change without a redeploy.
-- ===========================================================================

INSERT INTO plans (id, name, tag, badge, description, price_minor, currency, period, duration_days, unlimited, features, active, sort_order)
VALUES
('monthly_unlimited', 'Monthly All-Access Pass', 'UNLIMITED PITCHROOMS', 'Most Popular',
 'Unlimited pitchrooms and events for 30 days across all brands, investors, and hiring employers.',
 49900, 'USD', 'per month', 30, 1,
 JSON_ARRAY(
   'Unlimited Live Pitch Room presentations every month',
   'Pitch to unlimited Brands, Investors & Hiring Teams',
   'Verified Seller Pro Badge across all proposal lists',
   'Priority Pitch Deck queue in live buyer review sessions',
   'Full live scorecard breakdown & buyer feedback analytics',
   'Zero per-event fees across all 3 ecosystems (AB, SI, EE)',
   'Dedicated Pitch Concierge support & tech check'
 ), 1, 1),
('single_event', 'Single Event Pitch Pass', 'PAY AS YOU PITCH', 'Flexible Access',
 'Full access to pitch, present live, and enter one specific event or pitchroom.',
 9900, 'USD', 'single event', 365, 0,
 JSON_ARRAY(
   '1 Live Pitch Room admission for the selected event',
   'Official live pitch + Q&A presenter slot',
   'Full proposal deck submission & brand brief review',
   'Official Buyer Scorecard evaluation & feedback access',
   'Verified Event Participation Certificate & tax invoice'
 ), 1, 2)
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO slot_pricing (vertical, position, title, description, fee_minor, currency, active) VALUES
('ab', 1, 'Premium Position #1', 'First presenter — maximum buyer attention and the full evaluation window.', 1500000, 'INR', 1),
('ab', 2, 'Premium Position #2', 'Second presenter — strong recall before the buyer panel settles.', 1000000, 'INR', 1),
('ab', 3, 'Premium Position #3', 'Third presenter — premium placement in the first half of the agenda.', 750000, 'INR', 1),
('ab', 4, 'Standard Position #4', 'Standard allocated position based on shortlist evaluation score.', 0, 'INR', 1),
('ab', 5, 'Standard Position #5', 'Standard allocated position based on shortlist evaluation score.', 0, 'INR', 1),
('si', 1, 'Premium Position #1', 'First to pitch the investor panel.', 1500000, 'INR', 1),
('si', 2, 'Premium Position #2', 'Second pitch slot.', 1000000, 'INR', 1),
('si', 3, 'Premium Position #3', 'Third pitch slot.', 750000, 'INR', 1),
('si', 4, 'Standard Position #4', 'Standard allocated position.', 0, 'INR', 1),
('si', 5, 'Standard Position #5', 'Standard allocated position.', 0, 'INR', 1),
('ee', 1, 'Premium Position #1', 'First candidate to present to the hiring panel.', 1500000, 'INR', 1),
('ee', 2, 'Premium Position #2', 'Second presenter slot.', 1000000, 'INR', 1),
('ee', 3, 'Premium Position #3', 'Third presenter slot.', 750000, 'INR', 1),
('ee', 4, 'Standard Position #4', 'Standard allocated position.', 0, 'INR', 1),
('ee', 5, 'Standard Position #5', 'Standard allocated position.', 0, 'INR', 1)
ON DUPLICATE KEY UPDATE title = VALUES(title), fee_minor = VALUES(fee_minor);

-- Recurring jobs. These run from the API process itself (inline after a
-- response, via the /internal/scheduler/tick endpoint, or the CLI daemon) —
-- no hosting-panel cron entry is required.
INSERT INTO scheduled_tasks (id, handler, description, interval_seconds, enabled, next_run_at) VALUES
('task-meeting-reminders', 'meeting.reminders',  'Queue 24h and 1h reminders for scheduled events', 300,  1, UTC_TIMESTAMP()),
('task-meeting-autostart', 'meeting.autostart',  'Move events into waiting room / live at start time', 60, 1, UTC_TIMESTAMP()),
('task-meeting-advance',   'meeting.advance',    'Advance the live room clock past expired stages',    30,  1, UTC_TIMESTAMP()),
('task-meeting-autoclose', 'meeting.autoclose',  'Close rooms that ran past their end time',           300, 1, UTC_TIMESTAMP()),
('task-pass-expiry',       'billing.passExpiry', 'Expire seller passes and notify holders',            3600, 1, UTC_TIMESTAMP()),
('task-opportunity-deadlines', 'opportunity.deadlines', 'Close opportunities whose deadline passed',   3600, 1, UTC_TIMESTAMP()),
('task-cleanup',           'system.cleanup',     'Prune expired OTPs, tokens, locks and stale logs',   86400, 1, UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE handler = VALUES(handler), description = VALUES(description);

INSERT INTO scheduler_locks (name, locked_at, locked_by, last_tick_at, ticks)
VALUES ('global', NULL, NULL, NULL, 0)
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO migrations (filename, applied_at) VALUES ('005_seed_reference.sql', UTC_TIMESTAMP())
    ON DUPLICATE KEY UPDATE applied_at = applied_at;
